name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js with the correct version (>= 20.0.0 for compatibility)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Clear Yarn cache to avoid caching issues
      - name: Clear Yarn cache
        run: yarn cache clean

      # Step 4: Install dependencies using Yarn
      - name: Install Dependencies
        run: |
          yarn install

      # Step 5: Build the frontend using Yarn
      - name: Build the frontend
        run: |
          yarn build

      # Step 6: Build Docker image using Podman
      - name: Build Docker image with Podman
        run: |
          podman build -t localhost/frontend-image:latest .
        working-directory: "."

      # Step 7: Load image into Minikube
      - name: Load Image into Minikube
        run: |
          minikube image load localhost/frontend-image:latest  # Required for Minikube with Podman

      # Step 8: Set up Kubernetes credentials using kubeconfig
      - name: Set up Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Step 9: Deploy to Kubernetes (Minikube)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-ingress.yaml

      # Step 10: Restart Deployment
      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment frontend-deployment

      # Step 11: Verify Deployment
      - name: Verify Deployment
        run: kubectl get pods
