name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # Use self-hosted runner

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Clear Yarn cache
      - name: Clear Yarn cache
        run: yarn cache clean

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          yarn install

      # Step 5: Build the Frontend
      - name: Build the frontend
        run: |
          yarn build

      # Step 6: Ensure Minikube Cluster is Running with cri-o Driver
      - name: Ensure Minikube Cluster is Running with cri-o Driver
        run: |
          minikube start --driver=podman --container-runtime=cri-o

      # Step 7: Build Frontend Docker Image with Podman
      - name: Build Docker Image with Podman
        run: |
          podman build -t localhost/frontend-image:latest .

      # Step 8: Save the Frontend Image as a Tar File
      - name: Save Podman Image as Tar
        run: |
          podman save -o frontend-image.tar localhost/frontend-image:latest

      # Step 9: Load the Frontend Image into Minikube
      - name: Load Image into Minikube
        run: |
          minikube image load frontend-image.tar

      # Step 10: Set up Kubernetes Config
      - name: Set up Kubernetes Config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Step 11: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-ingress.yaml

      # Step 12: Restart Deployment
      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment frontend-deployment

      # Step 13: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods --all-namespaces
