name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version here

      - name: Install Dependencies
        run: |
          yarn install  # Use `npm install` if you're using npm

      - name: Build the frontend
        run: |
          yarn build  # Use `npm run build` if you're using npm

      - name: Build Docker image
        run: |
          podman build -t frontend-image .

      - name: Push Docker image
        run: |
          podman push frontend-image

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-ingress.yaml
